=== soaresCecilia/DAW2020/TPC4/ProjectRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="meta"/>
        <xs:element ref="team"/>
        <xs:element ref="abstract"/>
        <xs:element ref="deliverables"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="key"/>
        <xs:element ref="title"/>
        <xs:element minOccurs="0" ref="subtitle"/>
        <xs:element ref="bdate"/>
        <xs:element ref="edate"/>
        <xs:element ref="supervisor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="key" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="subtitle" type="xs:string"/>
  <xs:element name="bdate" type="xs:string"/>
  <xs:element name="edate" type="xs:string"/>
  <xs:element name="supervisor">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.supervisor"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.supervisor">
    <xs:attribute name="url"/>
  </xs:attributeGroup>
  <xs:element name="team">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="member"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="member">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="email"/>
        <xs:element minOccurs="0" ref="link"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.member"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:attributeGroup name="attlist.member">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="abstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="i"/>
        <xs:element ref="u"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="i">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="u"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="u"/>
        <xs:element ref="i"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="u">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="i"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="ilink">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.ilink"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.ilink">
    <xs:attribute name="ref" use="required" type="xs:IDREF"/>
  </xs:attributeGroup>
  <xs:element name="link">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.link"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.link">
    <xs:attribute name="url" use="required"/>
  </xs:attributeGroup>
  <xs:element name="deliverables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== soaresCecilia/DAW2020/TPC5/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<pr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/ceciliasoares/Documents/Universidade/4Ano/1semestre/DAW/DAW2020/TPC5/ProjectRecord.xsd">
    <meta>
        <key>Project Record</key>
        <title>httpServer and Json-server Fast API</title>
        <bdate>14 de Novembro</bdate>
        <edate>14 de Novembro</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr"/>
        
    </meta>
    <team>
        <member id="a34900">
            <name>Cecília da Conceição de Oliveira Soares</name>
            <email>cecilia.oliveira.soares@gmail.com</email>
            <link url="https://github.com/soaresCecilia"/>
        </member>
    </team>
    <abstract>
        <p>O presente trabalho destinou-se à criação de uma aplicação web que se destina a tornar o 
        <i>dataset Escola de Música </i> todo navegável. Esta aplicação é possível através da comunicação 
        do nosso servidor httpServer com um <i> Json-server</i>, respondendo com páginas html onde apresenta 
        a informação obtida. </p>
        Em primeiro lugar, criamos duas estruturas de dados, <i>hashTables</i>, que denominamos 
        de <i>myHashInst</i> e <i>myHashCurso</i>, sendo que a primeira mapeia o id de um instrumento 
        no seu nome, e a segunda mapeia o id do Curso na sua designação. </p>
        Em segundo lugar, carregamos as mencionadas estruturas de dados quando o servidor é iniciado, 
        através do método <i>myFillMap</i> que faz um <b>GET<b> da informação contida na lista dos cursos 
        e retira os dados necessários. Estes dados permitem-nos saber qual a designação do curso que o aluno 
        frequenta, o que nos facilita a tarefa de criação da página html do aluno, bem como fazer a correspondência 
        entre o nome do instrumento e o seu id, visto que essa informação não é passível de ser obtida através da 
        lista dos instrumentos.</p>
        <p> Depois de termos criado e preenchido estas estruturas auxiliares, todo o serviço se baseia em pedidos <b>GET</b>
        que o nosso servidor faz ao Json-server, passando-lhe o caminho absoluto da informação que pretende para construir
        a respectiva página <i>web</i>.</p>
        <p> Finalmente, resta mencionar que o nosso httpServer encontra-se na porta 4000 e o Json-server na porta 
        3001.</p>          
    </abstract>
    <deliverables>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC5/server.js"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC5/db.json"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC5/package-lock.json"/>
        <link url="https://github.com/soaresCecilia/DAW2020/tree/main/TPC5/node_modules"/>

        
    </deliverables>
</pr>

=== soaresCecilia/DAW2020/TPC8/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<pr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/ceciliasoares/Documents/Universidade/4Ano/1semestre/DAW/DAW2020/TPC8/ProjectRecord.xsd">
    <meta>
        <key>Project Record</key>
        <title>Upload Multiple Files</title>
        <bdate>7 de Dezembro</bdate>
        <edate>7 de Dezembro</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr"/>
        
    </meta>
    <team>
        <member id="a34900">
            <name>Cecília da Conceição de Oliveira Soares</name>
            <email>cecilia.oliveira.soares@gmail.com</email>
            <link url="https://github.com/soaresCecilia"/>
        </member>
    </team>
    <abstract>
        <p>O presente trabalho trabalho de casa tinha como objectivo executar o <i>upload</i> de múltiplos ficheiros.</p>
        <p>Para isso criamos a função <i>addFile<i>, que é chamada sempre que é pressionado o botão <b>Add File</p> e que 
        acrescenta ao formulário a parte de descrição do ficheiro e do carregamento do mesmo e inserimos essa informação 
        como o último filho do elemento em causa.<p>
        <p> Assim, é possível o utilizador escolha ficheiros de diferentes directorias, coisa que não é possível utilizando
        a opção <i>multiple<i> no formulário html quanod o <i>input</i> é um <i>file</i>.<p>       
    </abstract>
    <deliverables>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC8/servertpc.js"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC8/dbFiles.json"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC8/html-templates.js"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC8/public/imagens.js"/>      
    </deliverables>
</pr>

=== soaresCecilia/DAW2020/TPC4/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<pr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/ceciliasoares/Documents/Universidade/4Ano/1semestre/DAW/DAW2020/TPC4/ProjectRecord.xsd">
    <meta>
        <key>Project Record</key>
        <title>Node Server</title>
        <bdate>10 de Novembro</bdate>
        <edate>10 de Novembro</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr"/>
        
    </meta>
    <team>
        <member id="a34900">
            <name>Cecília da Conceição de Oliveira Soares</name>
            <email>cecilia.oliveira.soares@gmail.com</email>
            <link url="https://github.com/soaresCecilia"/>
        </member>
    </team>
    <abstract>
        <p>O presente trabalho visou a criação de várias páginas html a partir de um documento <b>xsl</b> 
            que aplica os seus sucessivos <i>templates</i> ao <i>dataset arq.xml</i> fornecido. </p>
        <p>Começamos por criar várias páginas html, sempre que encontramos no referido <i>dataset</i>, 
            um novo <b>ARQELEM</b>. Cada uma das páginas html é nomeada como <i>arqX.html</i>,
            sendo o X um número que aumenta sucessivamente.</p>
        <p>De seguida criamos um servidor em <b>node.js</b> que verifica se a expressão introduzida no 
           browser corresponde ao padrão <b>localhost:12346/arqs/X</b>, podendo X ser um número de 1 a 
            122 ou a palavra index, ambas as possibilidades podem ter ou não a extensão html.</p>
        <p>Finalmente, caso a página requerida não seja encontrada, esse erro é indicado através da nossa 
           página html de erro, criada para o efeito.</p>            
           
        <p/>
    </abstract>
    <deliverables>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC4/server.js"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC4/arq.xml"/>
        <link url="https://github.com/soaresCecilia/DAW2020/tree/main/TPC4/arqs"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC4/arqSitios.xsl"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC4/mymod.js"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC4/ProjectRecord.dtd"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC4/ProjectRecord.xsd"/>
        
    </deliverables>
</pr>

=== soaresCecilia/DAW2020/TPC6/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<pr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/ceciliasoares/Documents/Universidade/4Ano/1semestre/DAW/DAW2020/TPC6/ProjectRecord.xsd">
    <meta>
        <key>Project Record</key>
        <title>Gestor de Tarefas</title>
        <bdate>23 de Novembro</bdate>
        <edate>23 de Novembro</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr"/>
        
    </meta>
    <team>
        <member id="a34900">
            <name>Cecília da Conceição de Oliveira Soares</name>
            <email>cecilia.oliveira.soares@gmail.com</email>
            <link url="https://github.com/soaresCecilia"/>
        </member>
    </team>
    <abstract>
        <p>Com o presente trabalho criamos uma <i>Single PAge Application</i> <b>SPA</b> para uma lista de tarefas,  
        utilizando Node.js, que permitisse inserir, editar e remover tarefas, bem como marcá-las como realizadas 
        ou por realizar. </p>
        <p> Para efectuarmos este trabalho tivemos de estudar os <i>HTML forms</i>, os seus atributos, <i>labels</i> e 
        <i>controls</i> de modo a que as informações inseridas pelo utilizador nos respectivos formulários da aplicação
        fossem devidamente processadas.</p>
        <p>Ademais, a nossa página principal permite que o utilizador insira uma tarefa e que o mesmo visualize duas listas
        de tarefas agrupadas pelo seu estado (Realizadas e Não Realizadas), ordenadas pela sua descrição,
        e sempre que é criada uma nova tarefa é obrigatória a inserção do id e do estado da mesma.</p> 
        <p> Finalmente, na edição da tarefa não é possível alterar o id da mesma.</p>          
    </abstract>
    <deliverables>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC6/tpc6.js"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC6/static.js"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC6/package-lock.json"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC6/dbTarefas.json"/>
        <link url="https://github.com/soaresCecilia/DAW2020/blob/main/TPC6/package.json"/>
        <link url="https://github.com/soaresCecilia/DAW2020/tree/main/TPC6/node_modules"/>
        <link url="https://github.com/soaresCecilia/DAW2020/tree/main/TPC6/public"/>
    </deliverables>
</pr>

=== soaresCecilia/DAW2020/TPC7/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<pr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/ceciliasoares/Documents/Universidade/4Ano/1semestre/DAW/DAW2020/TPC7/ProjectRecord.xsd">
    <meta>
        <key>Project Record</key>
        <title>Mongo e API Express</title>
        <bdate>30 de Novembro</bdate>
        <edate>30 de Novembro</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr"/>
        
    </meta>
    <team>
        <member id="a34900">
            <name>Cecília da Conceição de Oliveira Soares</name>
            <email>cecilia.oliveira.soares@gmail.com</email>
            <link url="https://github.com/soaresCecilia"/>
        </member>
    </team>
    <abstract>
        <p>Com o presente trabalho criamos uma aplicação web que gere informação acerca dos alunos que 
        frequentam a disciplina de <i>Desenvolvimento de Aplicações Web</i>. Para isso, utilizamos a 
        <i>web application framework</i> <b>Express</b> que nos ajudou a criar uma <u>REST API</u> robusta e de forma rápida. </p>
        Além disso, exploramos ainda a base de dados <i>Mongo</i>, usando-a para guardar os dados dos alunos. </p>
        A presente aplicação permite-nos inserir, consultar, editar e remover os dados referente aos referidos alunos.</p>          
    </abstract>
    <deliverables>
        <link url="https://github.com/soaresCecilia/DAW2020/tree/main/TPC7/>
    </deliverables>
</pr>
